#GSO FORRIT
textfile = open('file.txt','w')
textfile.write('Python er ez')
textfile.close()
textfile = open('file.txt','a')
textfile.write(' Þetta er fyrsta forritið mitt í python ')
textfile.write(' og það var létt')
textfile.close()
textfile = open('file.txt','r')
print (textfile.read())
